language: go

go:
  - 1.7.x
  - 1.8.x

install:
- go get github.com/iotaledger/apibox/server
- go get github.com/iotaledger/apibox/worker

before_install:
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update

script:
- cd server;go test -v -covermode=count -coverprofile=coverage.out;cd ..
- cd worker;go test -v -covermode=count -coverprofile=coverage.out;cd ..

after_success:
- gometalinter -e bindata --deadline=1000s ./...
- goveralls -coverprofile=coverage.out -service=travis-ci

